### ISSUE TITLE
Let people vote and discuss on future topics

### ISSUE THREAD

**Issue by Baasie** [Virtual-Domain-driven-design/virtual-domain-driven-design#31] opened 2021-02-10 17:19 UTC
Do we keep sessionize now or do we need a new platform and integrate it?

https://www.upvoty.com/

https://hackerspad.net/software/upvoty/

**Comment by carousel** [comment] 2021-02-12 09:43
Honestly, I am a little bit confused with how sessionize works. Let's use something else

**Comment by Baasie** [comment] 2021-02-15 12:34
Yes I know @Max-Git is looking at upvoty as we speak. Do you have any ideas yourself @carousel ?

**Comment by carousel** [comment] 2021-02-15 14:29
@Baasie here's how I see this - the voting system represents randomizing of the topics. For a complex area like DDD, we should have a different way to select our future discussions. Something that will have structure and quality but at the same time stay open to the public and ideas. My suggestion is to use Slack (or something similar) and during a week briefly discuss and select suggested topics. 
This way, everybody will have a chance to suggest his favorite areas of interest, he/she will become a visible part of the VDD community, topics will be saved for later, and ideas will naturally emerge from the flow of ideas.

**Comment by yellowbrickc** [comment] 2021-03-01 08:59
The problem is, we have slack in place but the VirtualDDD channel is dead (AKA not working). Nobody is using it.
What we have in mind is a list of possible sessions/topics/guests with the current state (like proposed, chosen, planned). This list would give people the possibility to plan for the future or add new topics/guests. At the same time would also offer a possibility to vote so that we can get the "pulse". It would not lead to not having some sessions if we consider them interesting but we could offer and get some direct feedback (which we miss at the moment)

Maybe you have an idea about how to get the slack-communication working?

**Comment by carousel** [comment] 2021-03-01 11:51
It is weird that **slack** is not working. Can you give me more details? Maybe you had some kind of payment plan and it expired? Usually **slack** is free and advanced features are only paid. I was mentioning **slack** since it is mostly up for many of us during the whole workday, and it has nice features for collaboration (channels, voting, history, comments...). 

Br
Miro

**Comment by yellowbrickc** [comment] 2021-03-01 11:57
😆 I meant the communication is not working. People do not use it, do not ask questions or propose sessions. I didn't take it as a promotion, no worry, I think slack is a very helpful tool.

**Comment by carousel** [comment] 2021-03-01 11:58
Then let's market it and work on promotion. Can you share VDDD **slack** channel, please...

**Comment by yellowbrickc** [comment] 2021-03-01 13:49
This is the link to the slack-community, people should join the channel virtualDDD (I have no possibility to create a link for that)
https://join.slack.com/t/ddd-cqrs-es/shared_invite/zt-m3vf3alt-S3L~YUoIV88wekj6wSNrUQ

The problem with these links is that they expire (this expires in 6 days 😞 ) Somebody has already started to work on a better wy to join slack, but he is not done yet.

The slack/tweeter/meetup links are also on the virtualddd homepage. We just added the logos to the buttons to make them more prominent.

**Comment by yellowbrickc** [comment] 2021-03-22 14:29
I replaced the last link to sessionize (but as a sponsor) with the new Voting/Proposing link. I close this issue now.

**Closed by yellowbrickc** 2021-03-22 14:29 UTC
Labels: enhancement
